version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rahman
      - MYSQL_DATABASE=e_commerce
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
